var mongoose = require('mongoose');
// var Schema = mongoose.Schema;
var BaseSchema = require('./abstract').BaseSchema;

var util = require("util");
var EventEmitter = require("events").EventEmitter;

// var topic = require('./topicSchema');

var kodaSchema = new BaseSchema({
  Name:{
 type:String,
//  unique:true,
 required:true,
 trim:true
},
     lionDanceShow:[{
       helpLion:[{
         progress:{
           type:Number,
           default:10,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       lionDance:[{
         progress:{
           type:Number,
           default:20,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
         lionDancecont:[{
         progress:{
           type:Number,
           default:30,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       flipbook:[{
         progress:{
           type:Number,
           default:40,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       flipbookCont:[{
         progress:{
           type:Number,
           default:50,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       stepShown:[{
         progress:{
           type:Number,
           default:65,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       rearrangeMoves:[{
         progress:{
           type:Number,
           default:85,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       flipbookeffect:[{
         progress:{
           type:Number,
           default:100,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       success:[{
         progress:{
           type:Number,
           default:100,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }]
     }],
     visit:{
       type:Number
     },
     giraffeGuru:[{
       welcome:[{
         progress:{
           type:Number,
           default:8,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       giffGame:[{
         progress:{
           type:Number,
           default:15,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       typeOfChar1:[{
         progress:{
           type:Number,
           default:25,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       typeOfChar2:[{
         progress:{
           type:Number,
           default:30,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       typeOfChar3:[{
         progress:{
           type:Number,
           default:35,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       algorithm:[{
         progress:{
           type:Number,
           default:40,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       playGame2:[{
         progress:{
           type:Number,
           default:50,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       game2elements:[{
         progress:{
           type:Number,
           default:56,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       game2algorithm:[{
         progress:{
           type:Number,
           default:80,
           trim:true
         },
         visit:{
           type:Number,
           default:0,
           trim:true
         },
         timeSpend:{
           type:Number,
           default:0
         }
       }],
       success:[{
           progress:{
             type:Number,
             default:100,
             trim:true
           },
           visit:{
             type:Number,
             default:0,
             trim:true
           },
           timeSpend:{
             type:Number,
             default:0
           }
       }]
     }]
    });



// var koda = mongoose.model('koda', kodaSchema);




// specify the transform schema option
if (!kodaSchema.options.toObject) kodaSchema.options.toObject = {};
kodaSchema.options.toObject.transform = function (doc, ret, options) {
  // remove the _id of every document before returning the result
  ret.userID = ret._id;
  delete ret._id;
  delete ret.__v;
  return ret;
};

// module.export = kodaList;

module.exports = {
    koda : mongoose.model('koda',kodaSchema),
    };
